- hosts: halti-nodes
  become: yes
  become_method: sudo
  vars:
    halti_server: "http://10.1.7.241:4040"
  roles:
    - halti-agent
    - nodejs
    - haproxy
    - role: luotsi
      ssl: false

  # tasks:
  #   - name: Push certificate
  #     copy:
  #       content: "{{ ssl_certificate }}"
  #       dest: /etc/haproxy/cert.pem
  #       owner: root
  #       group: root
  #     register: ssl_certificate
