- hosts: halti-nodes
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - docker
    - halti-agent
    - nodejs
    - haproxy
    - role: luotsi
      ssl: false
    - telegraf
