- hosts: haltimaster
  user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - docker
    - mongodb
    - halti-master
    - influxdb
    - grafana
    - telegraf
