
---

- name: Remove halti-server
  docker:
    name: halti-master
    state: absent
    image: emblica/halti-master:latest

- name: Run halti-server
  docker:
    name: halti-master
    image: emblica/halti-server
    state: restarted
    restart_policy: always
    ports:
      - "{{ private_ip }}:{{ halti_master_port }}:{{ halti_master_port }}"
    links:
    - mongodb
    env:
      PRODUCTION: "yes"
      MONGO_URI: "mongodb://mongodb/halti"
      PORT: "{{ halti_master_port }}"
